# Generated by Django 5.2.4 on 2025-07-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HourLoggerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='end',
            field=models.CharField(max_length=20, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='log',
            name='start',
            field=models.CharField(max_length=20, verbose_name='Start'),
        ),
    ]
