# Generated by Django 5.2.4 on 2025-07-15 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('start', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Start')),
                ('end', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='End')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HourLoggerApp.job', verbose_name='Logs')),
            ],
            options={
                'db_table': 'Logs',
            },
        ),
    ]
