# Generated by Django 5.2.4 on 2025-08-14 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HourLoggerApp', '0002_alter_log_end_alter_log_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
